version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/tools"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "flake8*"
          - "black"
          - "isort"
          - "mypy"
          - "ruff"
