[metadata]
name = "dfint localization hook offsets"
version = "50.09 itch.io win64"
checksum = 0x6499dE1B

[offsets]
# translation
string_copy = 0xB740
string_copy_n = 0xB760
string_append = 0xB510
string_append_0 = 0xB530
string_append_n = 0xB8A0
convert_ulong_to_string = 0x3B62E0
addst = 0x7EEB60
addst_top = 0x7EEC40
addcoloredst = 0x7EE7F0
addst_flag = 0x7EE8D0
# search
standardstringentry = 0x8F4A70
simplify_string = 0x3B6C70
upper_case_string = 0x3B6FB0
lower_case_string = 0x3B6E10
capitalize_string_words = 0x3B7150
capitalize_string_first_word = 0x3B73D0
# ttf
addchar = 0x56AA0
addchar_top = 0x111A50
add_texture = 0xF1F260
gps_allocate = 0x621310
cleanup_arrays = 0x621130
screen_to_texid = 0x61A670
screen_to_texid_top = 0x61A860
# game state
loading_world_new_game_loop = 0xA74EC0
loading_world_continuing_game_loop = 0x5C4840
loading_world_start_new_game_loop = 0x5C2AF0
menu_interface_loop = 0x192250
# keybinding shift
keybinding = 370
