[metadata]
name = "dfint localization hook offsets"
version = "50.09 steam win64"
checksum = 0x6499d519

[offsets]
# translation
string_copy = 0xB7B0
string_copy_n = 0xB7D0
string_append = 0xB580
string_append_0 = 0xB5A0
string_append_n = 0xB910
convert_ulong_to_string = 0x3B8B70
addst = 0x7F1680
addst_top = 0x7F1760
addcoloredst = 0x7F1310
addst_flag = 0x7F13F0
# search
standardstringentry = 0x8F7590
simplify_string = 0x3B96A0
upper_case_string = 0x3B99E0
lower_case_string = 0x3B9840
capitalize_string_words = 0x3B9B80
capitalize_string_first_word = 0x3B9E00
# ttf
addchar = 0x56B10
addchar_top = 0x111AC0
add_texture = 0xF23900
gps_allocate = 0x623D40
cleanup_arrays = 0x623B60
screen_to_texid = 0x61D0A0
screen_to_texid_top = 0x61D290
# game state
loading_world_new_game_loop = 0xA79560
loading_world_continuing_game_loop = 0x5C7270
loading_world_start_new_game_loop = 0x5C5520
menu_interface_loop = 0x192610
# keybinding shift
keybinding = 370
