[metadata]
name = "dfint localization hook offsets"
version = "50.08 itch.io win64"
checksum = 0x64504278

[offsets]
# translation
string_copy = 0xB830
string_copy_n = 0xB850
string_append = 0xB5F0
string_append_0 = 0xB610
string_append_n = 0xB990
convert_ulong_to_string = 0x391440
addst = 0x7C28F0
addst_top = 0x7C29D0
addcoloredst = 0x7C25A0
addst_flag = 0x7C2680
# search
standardstringentry = 0x8C15A0
simplify_string = 0x391DE0
upper_case_string = 0x392120
lower_case_string = 0x391F80
capitalize_string_words = 0x3922C0
capitalize_string_first_word = 0x392540
# ttf
addchar = 0x561E0
addchar_top = 0xF3D50
add_texture = 0xED7470
gps_allocate = 0x5FCCF0
cleanup_arrays = 0x5FCB10
screen_to_texid = 0x5F4D80
screen_to_texid_top = 0x5F4F70
# game state
loading_world_new_game_loop = 0xA46E20
loading_world_continuing_game_loop = 0x59F140
loading_world_start_new_game_loop = 0x59CD90
menu_interface_loop = 0x172E20
# keybinding shift
keybinding = 370
