[metadata]
name = "dfint localization hook offsets"
version = "50.10 steam win64"
checksum = 0x6507BEAC

[offsets]
# translation
string_copy = 0xBAB0
string_copy_n = 0xBAD0
string_append = 0xB880
string_append_0 = 0xB8A0
string_append_n = 0xBC10
convert_ulong_to_string = 0x3C14E0
addst = 0x801230
addst_top = 0x801310
addcoloredst = 0x800EC0
addst_flag = 0x800FA0
# search
standardstringentry = 0x9070D0
simplify_string = 0x3C2010
upper_case_string = 0x3C2350
lower_case_string = 0x3C21B0
capitalize_string_words = 0x3C24F0
capitalize_string_first_word = 0x3C2770
# ttf
addchar = 0x56A20
addchar_top = 0x117FD0
add_texture = 0xF355B0
gps_allocate = 0x631520
cleanup_arrays = 0x631340
screen_to_texid = 0x62A700
screen_to_texid_top = 0x62A8F0
# game state
loading_world_new_game_loop = 0xA89630
loading_world_continuing_game_loop = 0x5D4EA0
loading_world_start_new_game_loop = 0x5D31A0
menu_interface_loop = 0x19BCB0
# keybinding shift
keybinding = 370
