[metadata]
name = "dfint localization hook offsets"
version = "50.11 classic win64"
checksum = 0x65190584

[offsets]
# translation
string_copy = 0xBA90
string_copy_n = 0xBAB0
string_append = 0xB860
string_append_0 = 0xB880
string_append_n = 0xBBF0
convert_ulong_to_string = 0x3BA8B0
addst = 0x7FADE0
addst_top = 0x7FAEC0
addcoloredst = 0x7FAA70
addst_flag = 0x7FAB50
# search
standardstringentry = 0x9006C0
simplify_string = 0x3BB240
upper_case_string = 0x3BB580
lower_case_string = 0x3BB3E0
capitalize_string_words = 0x3BB720
capitalize_string_first_word = 0x3BB9A0
# ttf
addchar = 0x56A60
addchar_top = 0x118030
add_texture = 0xF2E220
gps_allocate = 0x62AF30
cleanup_arrays = 0x62AD50
screen_to_texid = 0x624110
screen_to_texid_top = 0x624300
# game state
loading_world_new_game_loop = 0xA81D10
loading_world_continuing_game_loop = 0x5CE820
loading_world_start_new_game_loop = 0x5CCB20
menu_interface_loop = 0x19BA20
# keybinding shift
keybinding = 370
