[metadata]
name = "dfint localization hook offsets"
version = "50.10 itch.io win64"
checksum = 0x6507C6DE

[offsets]
# translation
string_copy = 0xBA30
string_copy_n = 0xBA50
string_append = 0xB800
string_append_0 = 0xB820
string_append_n = 0xBB90
convert_ulong_to_string = 0x3BEDF0
addst = 0x7FE8C0
addst_top = 0x7FE9A0
addcoloredst = 0x7FE550
addst_flag = 0x7FE630
# search
standardstringentry = 0x904760
simplify_string = 0x3BF780
upper_case_string = 0x3BFAC0
lower_case_string = 0x3BF920
capitalize_string_words = 0x3BFC60
capitalize_string_first_word = 0x3BFEE0
# ttf
addchar = 0x569A0
addchar_top = 0x117F50
add_texture = 0xF310C0
gps_allocate = 0x62EC90
cleanup_arrays = 0x62EAB0
screen_to_texid = 0x627E70
screen_to_texid_top = 0x628060
# game state
loading_world_new_game_loop = 0xA85140
loading_world_continuing_game_loop = 0x5D2610
loading_world_start_new_game_loop = 0x5D0910
menu_interface_loop = 0x19B950
# keybinding shift
keybinding = 370
